/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package browser;
import java.util.ArrayList;

/**
 *
 * @author hp
 */
public class NewJFrame extends javax.swing.JFrame {
    public static String comValues; //comment values
    public static ArrayList<String> lblEvaluate=new ArrayList();
    public static ArrayList<Integer> evalScore=new ArrayList();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        lblText1 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        lblText3 = new javax.swing.JLabel();
        lblText4 = new javax.swing.JLabel();
        lblText5 = new javax.swing.JLabel();
        lblText6 = new javax.swing.JLabel();
        lblText7 = new javax.swing.JLabel();
        lblText8 = new javax.swing.JLabel();
        lblText9 = new javax.swing.JLabel();
        lblText10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 313));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 143, 295, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("正在评价的教师");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 143, -1, -1));

        jComboBox1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.setSelectedIndex(4);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jComboBox2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox2.setSelectedIndex(4);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jComboBox3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox3.setSelectedIndex(4);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jComboBox4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox4.setSelectedIndex(4);
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        jComboBox5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox5.setSelectedIndex(4);
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jComboBox6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox6.setSelectedIndex(4);
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, -1, -1));

        jComboBox7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox7.setSelectedIndex(4);
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        jComboBox8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox8.setSelectedIndex(4);
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, -1, -1));

        jComboBox9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox9.setSelectedIndex(4);
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, -1, -1));

        jComboBox10.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox10.setSelectedIndex(4);
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, -1, -1));

        jButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton1.setText("提交");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        lblText1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText1.setText("jLabel1");
        getContentPane().add(lblText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        lblText2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText2.setText("jLabel1");
        getContentPane().add(lblText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        lblText3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText3.setText("jLabel1");
        getContentPane().add(lblText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        lblText4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText4.setText("jLabel1");
        getContentPane().add(lblText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        lblText5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText5.setText("jLabel1");
        getContentPane().add(lblText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        lblText6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText6.setText("jLabel1");
        getContentPane().add(lblText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        lblText7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText7.setText("jLabel1");
        getContentPane().add(lblText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        lblText8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText8.setText("jLabel1");
        getContentPane().add(lblText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        lblText9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText9.setText("jLabel1");
        getContentPane().add(lblText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        lblText10.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblText10.setText("jLabel1");
        getContentPane().add(lblText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Events.Submittion();
        if(Start.values.size()==0){
        NewJFrame1 newJFrame1=new NewJFrame1();
        newJFrame1.setVisible(true);
        Events.Initialization2();
        this.setVisible(false);
        
        
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox10;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    public static javax.swing.JComboBox jComboBox4;
    public static javax.swing.JComboBox jComboBox5;
    public static javax.swing.JComboBox jComboBox6;
    public static javax.swing.JComboBox jComboBox7;
    public static javax.swing.JComboBox jComboBox8;
    public static javax.swing.JComboBox jComboBox9;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblText1;
    public static javax.swing.JLabel lblText10;
    public static javax.swing.JLabel lblText2;
    public static javax.swing.JLabel lblText3;
    public static javax.swing.JLabel lblText4;
    public static javax.swing.JLabel lblText5;
    public static javax.swing.JLabel lblText6;
    public static javax.swing.JLabel lblText7;
    public static javax.swing.JLabel lblText8;
    public static javax.swing.JLabel lblText9;
    // End of variables declaration//GEN-END:variables
}
